### ISSUE TITLE
simple clic : the robot is not moving the right way !

### ISSUE THREAD

**Issue by Fabien-B** [ENACRobotique/pygargue#2]
Not many conditions tested, but at least at the startup of test.py on the raspi and pygrague on the control pc, if the user command the robot by a simple clic (ie it does not specify the angle), the robot move the wrong way along the X axis, symmetrically from the middle of the table.

**Comment by guilhembn** [comment]
Confirmed, I saw this behaviour yesterday too.

**Comment by guilhembn** [comment]
Fixed bb75894b9867cf88d6119eb784a2775b92b05aa2
